steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', '--single-branch', '--branch',
         'main','https://$$USERNAME:$$PASSWORD@github.com/k-root/mlops-cicd-google-vertex-doc.git',
         '--depth', '1',
         '--verbose']
  secretEnv: ['USERNAME', 'PASSWORD']
  id: 'Clone Repository'
  
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', '*.py', '*.yaml', 'gs://springml-notebook-testing-mlops-artifacts/pipeline_root/chicago-taxi-pipe/modules']
  dir: 'mlops-cicd-google-vertex-doc'
  id: 'Copy Modules'
  waitFor: ['Clone Repository']


- name: 'gcr.io/springml-notebook-testing/mlops-vertex-kfp:latest'
  # entrypoint: 'python'
  args: ['python', 'build_and_run_pipeline.py' ]
  dir: 'mlops-cicd-google-vertex-doc'
  id: 'Compile and Run Pipeline'
  waitFor: ['Copy Modules']

availableSecrets:
  secretManager:
  - versionName: projects/746365374287/secrets/git_passkey
    env: 'PASSWORD'
  - versionName: projects/746365374287/secrets/git_username
    env: 'USERNAME'
options:
  logging: CLOUD_LOGGING_ONLY