steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', '--single-branch', '--branch',
         '${_BRANCH}','${_REPO_URL}',
         '--depth', '1',
         '--verbose']
  id: 'Clone Repository'
  
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', '*.py', '*.yaml', 'gs://${_BUCKET_NAME}/${_PIPELINE_ROOT}/modules']
  dir: '${_REPO_NAME}'
  id: 'Copy Modules'
  waitFor: ['Clone Repository']


- name: 'gcr.io/${_PROJECT}/mlops-vertex-kfp:latest'
  entrypoint: 'python'
  args: [ 'build_and_run_pipeline.py'
        ]
  dir: '${_REPO_NAME}'
  id: 'Compile and Run Pipeline'
  waitFor: ['Copy Modules']
substitutions: 
    _PROJECT=springml-notebook-testing,\
    _REGION=us-central1,\
    _BUCKET_NAME= springml-notebook-testing-mlops-artifacts,\
    _PIPELINE_NAME=mlops-cicd,\
    _PIPELINE_ROOT=pipeline_root/chicago-taxi-pipe,\
    _REPO_NAME=mlops-cicd-google-vertex-doc,\
    _REPO_URL=https://github.com/k-root/mlops-cicd-google-vertex-doc.git,\
    _BRANCH=master,\